[package]
name = "topgrade"
description = "Upgrade all the things"
license-file = "LICENCE"
repository = "https://github.com/r-darwish/topgrade"
version = "0.6.0"
authors = ["Roey Darwish Dror <roey.ghost@gmail.com>"]
exclude = ["doc/screenshot.gif"]

[dependencies]
directories = "0.10.0"
failure = "0.1.1"
failure_derive = "0.1.1"
serde = "1.0.66"
serde_derive = "1.0.66"
termion = "1.5.1"
toml = "0.4.6"
which = "2.0.0"
shellexpand = "1.0.0"
