[package]
name = "topgrade"
description = "Upgrade all the things"
categories = ["os"]
keywords = ["upgrade", "update"]
license-file = "LICENSE"
repository = "https://github.com/r-darwish/topgrade"
version = "3.0.0"
authors = ["Roey Darwish Dror <roey.ghost@gmail.com>"]
exclude = ["doc/screenshot.gif"]
edition = "2018"
readme = "README.md"

[dependencies]
directories = "2.0.1"
failure = "0.1.5"
failure_derive = "0.1.5"
serde = { version = "1.0.92", features = ["derive"] }
toml = "0.5.1"
which_crate = { version = "2.0.1", package =  "which" }
shellexpand = "1.0.0"
structopt = "0.3.0"
log = "0.4.6"
walkdir = "2.2.7"
console = "0.8.0"
self_update_crate = { version = "0.6.0", optional = true, package =  "self_update" }
lazy_static = "1.3.0"
rust-ini = "0.13.0"
chrono = "0.4.6"
tokio = "0.1.21"
tokio-process = "0.2.3"
futures = "0.1.27"
openssl-probe = { version = "0.1.2", optional = true }
pretty_env_logger = "0.3.0"
glob = "0.3.0"

[target.'cfg(unix)'.dependencies]
nix = "0.15.0"

[profile.release]
lto = true

[features]
default = []

self-update = ["self_update_crate", "openssl-probe"]
