[package]
name = "topgrade"
description = "Upgrade all the things"
license-file = "LICENCE"
repository = "https://github.com/r-darwish/topgrade"
version = "0.17.0"
authors = ["Roey Darwish Dror <roey.ghost@gmail.com>"]
exclude = ["doc/screenshot.gif"]

[dependencies]
directories = "1.0.2"
failure = "0.1.3"
failure_derive = "0.1.3"
serde = "1.0.80"
serde_derive = "1.0.80"
toml = "0.4.8"
which = "2.0.0"
shellexpand = "1.0.0"
structopt = "0.2.12"
log = "0.4.6"
env_logger = "0.5.13"
term_size = "0.3.1"
termcolor = "1.0.4"
walkdir = "2.2.6"
console = "0.6.2"

[target.'cfg(unix)'.dependencies]
nix = "0.11.0"
lazy_static = "1.1.0"

[profile.release]
lto = true
