[package]
name = "topgrade"
description = "Upgrade all the things"
license-file = "LICENSE"
repository = "https://github.com/r-darwish/topgrade"
version = "1.6.0"
authors = ["Roey Darwish Dror <roey.ghost@gmail.com>"]
exclude = ["doc/screenshot.gif"]
edition = "2018"

[dependencies]
directories = "1.0.2"
failure = "0.1.5"
failure_derive = "0.1.5"
serde = { version = "1.0.85", features = ["derive"] }
toml = "0.4.10"
which_crate = { version = "2.0.1", package =  "which" }
shellexpand = "1.0.0"
structopt = "0.2.14"
log = "0.4.6"
env_logger = "0.6.0"
walkdir = "2.2.7"
console = "0.7.5"
self_update_crate = { version = "0.5.1", optional = true, package =  "self_update" }
lazy_static = "1.2.0"

[target.'cfg(unix)'.dependencies]
nix = "0.13.0"

[profile.release]
lto = true

[features]
default = []

self-update = ["self_update_crate"]
